const birthRecords = [
    {
      id: "B001",
      childName: "Aisha Kapoor",
      dob: "2023-12-15",
      tob: "14:30 PM",
      gender: "Female",
      weight: "2.8 kg",
      motherName: "Priya Kapoor",
      motherId: "M789",
      fatherName: "Rajiv Kapoor",
      fatherId: "F012",
      doctorName: "Dr. Patel",
      hospitalName: "Max Hospital",
      roomNumber: "205",
      notes: "Healthy baby girl",
    },
    {
      id: "B002",
      childName: "Rohan Malhotra",
      dob: "2024-02-09",
      tob: "07:15 AM",
      gender: "Male",
      weight: "3.2 kg",
      motherName: "Sonia Malhotra",
      motherId: "M345",
      fatherName: "Vikram Malhotra",
      fatherId: "F678",
      doctorName: "Dr. Khanna",
      hospitalName: "Apollo Hospital",
      roomNumber: "310",
      notes: "Healthy baby boy",
    },
    {
      id: "B003",
      childName: "Priya Desai",
      dob: "2022-08-21",
      tob: "11:00 AM",
      gender: "Female",
      weight: "2.9 kg",
      motherName: "Seema Desai",
      motherId: "M901",
      fatherName: "Atul Desai",
      fatherId: "F354",
      doctorName: "Dr. Mehta",
      hospitalName: "Fortis Hospital",
      roomNumber: "402",
      notes: "Healthy baby girl",
    },
    {
      id: "B004",
      childName: "Aarav Singh",
      dob: "2024-04-25",
      tob: "05:45 AM",
      gender: "Male",
      weight: "3.7 kg",
      motherName: "Anjali Singh",
      motherId: "M567",
      fatherName: "Jasprit Singh",
      fatherId: "F123",
      doctorName: "Dr. Sharma",
      hospitalName: "Columbia Asia Hospital",
      roomNumber: "108",
      notes: "Healthy baby boy",
    },
    {
      id: "B005",
      childName: "Kiara Patel",
      dob: "2023-10-10",
      tob: "18:00 PM",
      gender: "Female",
      weight: "3.1 kg",
      motherName: "Neha Patel",
      motherId: "M234",
      fatherName: "Mitesh Patel",
      fatherId: "F890",
      doctorName: "Dr. Shah",
      hospitalName: "Lilavati Hospital",
      roomNumber: "201",
      notes: "Healthy baby girl",
    },
    {
      id: "B006",
      childName: "Vivaan Joshi",
      dob: "2024-03-18",
      tob: "10:30 AM",
      gender: "Male",
      weight: "3.4 kg",
      motherName: "Manisha Joshi",
      motherId: "M780",
      fatherName: "Rahul Joshi",
      fatherId: "F456",
      doctorName: "Dr. Iyer",
      hospitalName: "Wockhardt Hospital",
      roomNumber: "309",
      notes: "Healthy baby boy",
    },
    {
      id: "B007",
      childName: "Aryan Sharma",
      dob: "2023-07-12",
      tob: "09:45 AM",
      gender: "Male",
      weight: "3.0 kg",
      motherName: "Nisha Sharma",
      motherId: "M567",
      fatherName: "Amit Sharma",
      fatherId: "F123",
      doctorName: "Dr. Verma",
      hospitalName: "Manipal Hospital",
      roomNumber: "215",
      notes: "Healthy baby boy",
    },
    {
      id: "B008",
      childName: "Maya Verma",
      dob: "2023-05-05",
      tob: "16:20 PM",
      gender: "Female",
      weight: "2.7 kg",
      motherName: "Anita Verma",
      motherId: "M890",
      fatherName: "Ravi Verma",
      fatherId: "F456",
      doctorName: "Dr. Kulkarni",
      hospitalName: "Rainbow Hospital",
      roomNumber: "125",
      notes: "Healthy baby girl",
    },
    {
      id: "B009",
      childName: "Kabir Rao",
      dob: "2024-01-10",
      tob: "08:30 AM",
      gender: "Male",
      weight: "3.5 kg",
      motherName: "Rekha Rao",
      motherId: "M234",
      fatherName: "Suresh Rao",
      fatherId: "F789",
      doctorName: "Dr. Agarwal",
      hospitalName: "Narayana Health",
      roomNumber: "304",
      notes: "Healthy baby boy",
    },
    {
      id: "B010",
      childName: "Sanya Nair",
      dob: "2022-11-22",
      tob: "12:10 PM",
      gender: "Female",
      weight: "2.9 kg",
      motherName: "Sunita Nair",
      motherId: "M345",
      fatherName: "Arjun Nair",
      fatherId: "F678",
      doctorName: "Dr. Pillai",
      hospitalName: "Aster Hospital",
      roomNumber: "220",
      notes: "Healthy baby girl",
    },
    {
      id: "B011",
      childName: "Ahaan Gupta",
      dob: "2023-09-19",
      tob: "07:40 AM",
      gender: "Male",
      weight: "3.3 kg",
      motherName: "Pooja Gupta",
      motherId: "M456",
      fatherName: "Anil Gupta",
      fatherId: "F789",
      doctorName: "Dr. Das",
      hospitalName: "Medanta Hospital",
      roomNumber: "315",
      notes: "Healthy baby boy",
    },
    {
      id: "B012",
      childName: "Tara Bhatia",
      dob: "2023-03-08",
      tob: "15:00 PM",
      gender: "Female",
      weight: "2.8 kg",
      motherName: "Kavita Bhatia",
      motherId: "M567",
      fatherName: "Rakesh Bhatia",
      fatherId: "F890",
      doctorName: "Dr. Rao",
      hospitalName: "BLK Hospital",
      roomNumber: "405",
      notes: "Healthy baby girl",
    },
    {
      id: "B013",
      childName: "Yash Jain",
      dob: "2024-06-12",
      tob: "06:50 AM",
      gender: "Male",
      weight: "3.6 kg",
      motherName: "Meera Jain",
      motherId: "M678",
      fatherName: "Sanjay Jain",
      fatherId: "F123",
      doctorName: "Dr. Roy",
      hospitalName: "Holy Family Hospital",
      roomNumber: "210",
      notes: "Healthy baby boy",
    },
    {
      id: "B014",
      childName: "Isha Agarwal",
      dob: "2022-09-25",
      tob: "13:20 PM",
      gender: "Female",
      weight: "3.0 kg",
      motherName: "Nikita Agarwal",
      motherId: "M789",
      fatherName: "Rohit Agarwal",
      fatherId: "F234",
      doctorName: "Dr. Chawla",
      hospitalName: "Paras Hospital",
      roomNumber: "306",
      notes: "Healthy baby girl",
    },
    {
      id: "B015",
      childName: "Reyansh Kapoor",
      dob: "2023-01-18",
      tob: "09:00 AM",
      gender: "Male",
      weight: "3.4 kg",
      motherName: "Simran Kapoor",
      motherId: "M890",
      fatherName: "Arjun Kapoor",
      fatherId: "F345",
      doctorName: "Dr. Sinha",
      hospitalName: "Jaypee Hospital",
      roomNumber: "115",
      notes: "Healthy baby boy",
    },
    {
      id: "B016",
      childName: "Diya Bhatt",
      dob: "2024-07-22",
      tob: "14:45 PM",
      gender: "Female",
      weight: "2.9 kg",
      motherName: "Alka Bhatt",
      motherId: "M901",
      fatherName: "Raj Bhatt",
      fatherId: "F456",
      doctorName: "Dr. Reddy",
      hospitalName: "Metro Hospital",
      roomNumber: "201",
      notes: "Healthy baby girl",
    },
    {
      id: "B017",
      childName: "Arnav Mehta",
      dob: "2023-05-14",
      tob: "11:35 AM",
      gender: "Male",
      weight: "3.2 kg",
      motherName: "Jaya Mehta",
      motherId: "M123",
      fatherName: "Kunal Mehta",
      fatherId: "F678",
      doctorName: "Dr. Bhargava",
      hospitalName: "Sterling Hospital",
      roomNumber: "305",
      notes: "Healthy baby boy",
    },
    {
      id: "B018",
      childName: "Ria Patel",
      dob: "2022-10-30",
      tob: "17:25 PM",
      gender: "Female",
      weight: "2.7 kg",
      motherName: "Kiran Patel",
      motherId: "M234",
      fatherName: "Mahesh Patel",
      fatherId: "F789",
      doctorName: "Dr. Chaudhary",
      hospitalName: "Sahara Hospital",
      roomNumber: "102",
      notes: "Healthy baby girl",
    },
    {
      id: "B019",
      childName: "Krishna Iyer",
      dob: "2023-11-05",
      tob: "06:20 AM",
      gender: "Male",
      weight: "3.3 kg",
      motherName: "Megha Iyer",
      motherId: "M345",
      fatherName: "Sandeep Iyer",
      fatherId: "F012",
      doctorName: "Dr. Mukherjee",
      hospitalName: "SevenHills Hospital",
      roomNumber: "402",
      notes: "Healthy baby boy",
    },
    {
      id: "B020",
      childName: "Nisha Reddy",
      dob: "2024-04-01",
      tob: "13:10 PM",
      gender: "Female",
      weight: "3.1 kg",
      motherName: "Swati Reddy",
      motherId: "M456",
      fatherName: "Vikas Reddy",
      fatherId: "F123",
      doctorName: "Dr. Rao",
      hospitalName: "Global Hospital",
      roomNumber: "310",
      notes: "Healthy baby girl",
    },
    {
      id: "B021",
      childName: "Ayaan Das",
      dob: "2023-06-24",
      tob: "08:10 AM",
      gender: "Male",
      weight: "3.5 kg",
      motherName: "Shilpa Das",
      motherId: "M567",
      fatherName: "Rahul Das",
      fatherId: "F890",
      doctorName: "Dr. Singh",
      hospitalName: "Sunshine Hospital",
      roomNumber: "215",
      notes: "Healthy baby boy",
    },
    {
      id: "B022",
      childName: "Sia Roy",
      dob: "2022-12-12",
      tob: "14:40 PM",
      gender: "Female",
      weight: "2.8 kg",
      motherName: "Deepa Roy",
      motherId: "M678",
      fatherName: "Arvind Roy",
      fatherId: "F234",
      doctorName: "Dr. Banerjee",
      hospitalName: "Surya Hospital",
      roomNumber: "120",
      notes: "Healthy baby girl",
    },
    {
      id: "B023",
      childName: "Vivaan Kapoor",
      dob: "2023-03-26",
      tob: "09:55 AM",
      gender: "Male",
      weight: "3.2 kg",
      motherName: "Suman Kapoor",
      motherId: "M789",
      fatherName: "Rishi Kapoor",
      fatherId: "F345",
      doctorName: "Dr. Gupta",
      hospitalName: "Nanavati Hospital",
      roomNumber: "205",
      notes: "Healthy baby boy",
    },
    {
      id: "B024",
      childName: "Anaya Khan",
      dob: "2024-05-16",
      tob: "07:25 AM",
      gender: "Female",
      weight: "3.0 kg",
      motherName: "Nida Khan",
      motherId: "M890",
      fatherName: "Imran Khan",
      fatherId: "F678",
      doctorName: "Dr. Husain",
      hospitalName: "Kokilaben Hospital",
      roomNumber: "312",
      notes: "Healthy baby girl",
    },
    {
      id: "B025",
      childName: "Kabir Verma",
      dob: "2023-09-08",
      tob: "12:50 PM",
      gender: "Male",
      weight: "3.4 kg",
      motherName: "Reena Verma",
      motherId: "M123",
      fatherName: "Amit Verma",
      fatherId: "F456",
      doctorName: "Dr. Lal",
      hospitalName: "Jehangir Hospital",
      roomNumber: "408",
      notes: "Healthy baby boy",
    },
    {
      id: "B026",
      childName: "Zara Mehta",
      dob: "2022-07-15",
      tob: "18:30 PM",
      gender: "Female",
      weight: "2.7 kg",
      motherName: "Anju Mehta",
      motherId: "M234",
      fatherName: "Ravi Mehta",
      fatherId: "F789",
      doctorName: "Dr. Rathi",
      hospitalName: "Breach Candy Hospital",
      roomNumber: "310",
      notes: "Healthy baby girl",
    },
    {
      id: "B027",
      childName: "Aarush Gupta",
      dob: "2024-02-18",
      tob: "06:10 AM",
      gender: "Male",
      weight: "3.6 kg",
      motherName: "Neelam Gupta",
      motherId: "M345",
      fatherName: "Rajesh Gupta",
      fatherId: "F123",
      doctorName: "Dr. Arora",
      hospitalName: "Cloudnine Hospital",
      roomNumber: "207",
      notes: "Healthy baby boy",
    },
    {
      id: "B028",
      childName: "Meera Sinha",
      dob: "2023-12-25",
      tob: "10:15 AM",
      gender: "Female",
      weight: "2.8 kg",
      motherName: "Shalini Sinha",
      motherId: "M456",
      fatherName: "Vivek Sinha",
      fatherId: "F234",
      doctorName: "Dr. Saxena",
      hospitalName: "Artemis Hospital",
      roomNumber: "404",
      notes: "Healthy baby girl",
    },
    {
      id: "B029",
      childName: "Dev Arora",
      dob: "2023-11-07",
      tob: "09:20 AM",
      gender: "Male",
      weight: "3.3 kg",
      motherName: "Ritu Arora",
      motherId: "M567",
      fatherName: "Sunil Arora",
      fatherId: "F890",
      doctorName: "Dr. Kapoor",
      hospitalName: "Apollo Cradle",
      roomNumber: "310",
      notes: "Healthy baby boy",
    },
    {
      id: "B030",
      childName: "Sara Singh",
      dob: "2023-08-19",
      tob: "15:30 PM",
      gender: "Female",
      weight: "2.9 kg",
      motherName: "Nidhi Singh",
      motherId: "M678",
      fatherName: "Ajay Singh",
      fatherId: "F345",
      doctorName: "Dr. Chaudhary",
      hospitalName: "Sakra Hospital",
      roomNumber: "204",
      notes: "Healthy baby girl",
    },
    {
      id: "B031",
      childName: "Arjun Pandey",
      dob: "2024-01-29",
      tob: "11:40 AM",
      gender: "Male",
      weight: "3.4 kg",
      motherName: "Lata Pandey",
      motherId: "M789",
      fatherName: "Kishore Pandey",
      fatherId: "F123",
      doctorName: "Dr. Sood",
      hospitalName: "Hiranandani Hospital",
      roomNumber: "309",
      notes: "Healthy baby boy",
    },
    {
      id: "B032",
      childName: "Diya Chatterjee",
      dob: "2023-07-14",
      tob: "08:10 AM",
      gender: "Female",
      weight: "3.1 kg",
      motherName: "Mona Chatterjee",
      motherId: "M890",
      fatherName: "Amit Chatterjee",
      fatherId: "F456",
      doctorName: "Dr. Bose",
      hospitalName: "Fortis Malar",
      roomNumber: "310",
      notes: "Healthy baby girl",
    },
    {
      id: "B033",
      childName: "Ishaan Kapoor",
      dob: "2022-09-30",
      tob: "12:30 PM",
      gender: "Male",
      weight: "3.2 kg",
      motherName: "Pooja Kapoor",
      motherId: "M123",
      fatherName: "Vikram Kapoor",
      fatherId: "F789",
      doctorName: "Dr. Vohra",
      hospitalName: "Ruby Hall Clinic",
      roomNumber: "404",
      notes: "Healthy baby boy",
    },
    {
      id: "B034",
      childName: "Riya Shah",
      dob: "2024-03-21",
      tob: "13:20 PM",
      gender: "Female",
      weight: "3.0 kg",
      motherName: "Geeta Shah",
      motherId: "M456",
      fatherName: "Amit Shah",
      fatherId: "F234",
      doctorName: "Dr. Nanda",
      hospitalName: "Saifee Hospital",
      roomNumber: "208",
      notes: "Healthy baby girl",
    },
    {
      id: "B035",
      childName: "Arnav Joshi",
      dob: "2023-04-12",
      tob: "07:00 AM",
      gender: "Male",
      weight: "3.6 kg",
      motherName: "Megha Joshi",
      motherId: "M567",
      fatherName: "Rohit Joshi",
      fatherId: "F678",
      doctorName: "Dr. Saxena",
      hospitalName: "Holy Spirit Hospital",
      roomNumber: "315",
      notes: "Healthy baby boy",
    },
    {
      id: "B036",
      childName: "Ananya Rai",
      dob: "2022-12-10",
      tob: "16:45 PM",
      gender: "Female",
      weight: "2.9 kg",
      motherName: "Sangeeta Rai",
      motherId: "M678",
      fatherName: "Anil Rai",
      fatherId: "F789",
      doctorName: "Dr. Kulkarni",
      hospitalName: "KIMS Hospital",
      roomNumber: "204",
      notes: "Healthy baby girl",
    },
    {
      id: "B037",
      childName: "Aarav Desai",
      dob: "2024-02-02",
      tob: "05:30 AM",
      gender: "Male",
      weight: "3.5 kg",
      motherName: "Manisha Desai",
      motherId: "M234",
      fatherName: "Sanjay Desai",
      fatherId: "F456",
      doctorName: "Dr. Sen",
      hospitalName: "Fortis Hospital",
      roomNumber: "310",
      notes: "Healthy baby boy",
    },
    {
      id: "B038",
      childName: "Rhea Iyer",
      dob: "2023-06-20",
      tob: "14:50 PM",
      gender: "Female",
      weight: "3.1 kg",
      motherName: "Asha Iyer",
      motherId: "M345",
      fatherName: "Vikram Iyer",
      fatherId: "F789",
      doctorName: "Dr. Prasad",
      hospitalName: "MGM Hospital",
      roomNumber: "210",
      notes: "Healthy baby girl",
    },
    {
      id: "B039",
      childName: "Vivaan Khan",
      dob: "2022-08-15",
      tob: "11:15 AM",
      gender: "Male",
      weight: "3.0 kg",
      motherName: "Nida Khan",
      motherId: "M456",
      fatherName: "Imran Khan",
      fatherId: "F890",
      doctorName: "Dr. Haque",
      hospitalName: "Noble Hospital",
      roomNumber: "312",
      notes: "Healthy baby boy",
    },
    {
      id: "B040",
      childName: "Kiara Reddy",
      dob: "2023-10-05",
      tob: "17:40 PM",
      gender: "Female",
      weight: "2.9 kg",
      motherName: "Rekha Reddy",
      motherId: "M567",
      fatherName: "Suresh Reddy",
      fatherId: "F234",
      doctorName: "Dr. Gupta",
      hospitalName: "Sparsh Hospital",
      roomNumber: "102",
      notes: "Healthy baby girl",
    },
    {
      id: "B041",
      childName: "Yash Bhat",
      dob: "2024-04-20",
      tob: "08:20 AM",
      gender: "Male",
      weight: "3.4 kg",
      motherName: "Neha Bhat",
      motherId: "M678",
      fatherName: "Ravi Bhat",
      fatherId: "F123",
      doctorName: "Dr. Singh",
      hospitalName: "Care Hospital",
      roomNumber: "205",
      notes: "Healthy baby boy",
    },
    {
      id: "B042",
      childName: "Diya Thakur",
      dob: "2023-02-27",
      tob: "12:30 PM",
      gender: "Female",
      weight: "3.2 kg",
      motherName: "Sonal Thakur",
      motherId: "M789",
      fatherName: "Raj Thakur",
      fatherId: "F345",
      doctorName: "Dr. Sharma",
      hospitalName: "Narayana Health",
      roomNumber: "310",
      notes: "Healthy baby girl",
    },
    {
      id: "B043",
      childName: "Aryan Sharma",
      dob: "2022-11-18",
      tob: "06:15 AM",
      gender: "Male",
      weight: "3.5 kg",
      motherName: "Nisha Sharma",
      motherId: "M890",
      fatherName: "Amit Sharma",
      fatherId: "F456",
      doctorName: "Dr. Verma",
      hospitalName: "Rainbow Hospital",
      roomNumber: "215",
      notes: "Healthy baby boy",
    },
    {
      id: "B044",
      childName: "Meera Rao",
      dob: "2024-06-11",
      tob: "15:20 PM",
      gender: "Female",
      weight: "3.0 kg",
      motherName: "Anita Rao",
      motherId: "M123",
      fatherName: "Ravi Rao",
      fatherId: "F789",
      doctorName: "Dr. Kulkarni",
      hospitalName: "Max Hospital",
      roomNumber: "402",
      notes: "Healthy baby girl",
    },
    {
      id: "B045",
      childName: "Kabir Malhotra",
      dob: "2023-09-09",
      tob: "11:50 AM",
      gender: "Male",
      weight: "3.6 kg",
      motherName: "Sonia Malhotra",
      motherId: "M234",
      fatherName: "Vikram Malhotra",
      fatherId: "F678",
      doctorName: "Dr. Khanna",
      hospitalName: "Apollo Hospital",
      roomNumber: "310",
      notes: "Healthy baby boy",
    },
  ];
  
  export default birthRecords;
  