const deathRecords = [
    {
      id: "D001",
      deceasedName: "Ravi Kumar",
      dod: "2024-01-20",
      tod: "08:15 AM",
      gender: "Male",
      age: "68",
      causeOfDeath: "Pneumonia",
      doctorName: "Dr. Sharma",
      hospitalName: "Max Hospital",
      roomNumber: "210",
      notes: "Had underlying respiratory issues",
    },
    {
      id: "D002",
      deceasedName: "Sunita Patel",
      dod: "2023-11-12",
      tod: "17:00 PM",
      gender: "Female",
      age: "52",
      causeOfDeath: "Car Accident",
      doctorName: "Dr. Mehta",
      hospitalName: "Apollo Hospital",
      roomNumber: "104",
      notes: "Brought in critical condition",
    },
    {
      id: "D003",
      deceasedName: "Vikram Desai",
      dod: "2022-07-05",
      tod: "12:45 PM",
      gender: "Male",
      age: "81",
      causeOfDeath: "Cancer",
      doctorName: "Dr. Joshi",
      hospitalName: "Fortis Hospital",
      roomNumber: "401",
      notes: "Long battle with illness",
    },
    {
      id: "D004",
      deceasedName: "Anjali Singh",
      dod: "2024-04-08",
      tod: "22:30 PM",
      gender: "Female",
      age: "40",
      causeOfDeath: "Heart Failure",
      doctorName: "Dr. Kapoor",
      hospitalName: "Columbia Asia Hospital",
      roomNumber: "302",
      notes: "Sudden cardiac episode",
    },
    {
      id: "D005",
      deceasedName: "Mitesh Patel",
      dod: "2023-09-25",
      tod: "05:15 AM",
      gender: "Male",
      age: "38",
      causeOfDeath: "Motorcycle Accident",
      doctorName: "Dr. Shah",
      hospitalName: "Lilavati Hospital",
      roomNumber: "112",
      notes: "Declared dead on arrival",
    },
    {
      id: "D006",
      deceasedName: "Manisha Joshi",
      dod: "2024-02-14",
      tod: "16:00 PM",
      gender: "Female",
      age: "72",
      causeOfDeath: "Stroke",
      doctorName: "Dr. Iyer",
      hospitalName: "Wockhardt Hospital",
      roomNumber: "207",
      notes: "Complications from previous stroke",
    },
    {
      id: "D007",
      deceasedName: "Rahul Mukherjee",
      dod: "2023-06-11",
      tod: "09:45 AM",
      gender: "Male",
      age: "55",
      causeOfDeath: "Kidney Failure",
      doctorName: "Dr. Das",
      hospitalName: "City Hospital",
      roomNumber: "408",
      notes: "Long-term kidney disease",
    },
    {
      id: "D008",
      deceasedName: "Priya Kapoor",
      dod: "2024-05-10",
      tod: "14:00 PM",
      gender: "Female",
      age: "61",
      causeOfDeath: "Cancer",
      doctorName: "Dr. Malhotra",
      hospitalName: "Max Hospital",
      roomNumber: "301",
      notes: "Peaceful passing after treatment",
    },
    {
      id: "D009",
      deceasedName: "Anil Verma",
      dod: "2023-03-18",
      tod: "11:30 AM",
      gender: "Male",
      age: "70",
      causeOfDeath: "Heart Attack",
      doctorName: "Dr. Sinha",
      hospitalName: "City Hospital",
      roomNumber: "502",
      notes: "Chronic heart disease",
    },
    {
      id: "D010",
      deceasedName: "Rita Sharma",
      dod: "2023-12-22",
      tod: "18:00 PM",
      gender: "Female",
      age: "65",
      causeOfDeath: "Diabetes Complications",
      doctorName: "Dr. Rao",
      hospitalName: "Global Hospital",
      roomNumber: "306",
      notes: "Long history of diabetes",
    },
    {
      id: "D011",
      deceasedName: "Suresh Gupta",
      dod: "2024-02-09",
      tod: "10:00 AM",
      gender: "Male",
      age: "76",
      causeOfDeath: "Alzheimer's Disease",
      doctorName: "Dr. Mehta",
      hospitalName: "Apollo Hospital",
      roomNumber: "110",
      notes: "Advanced stage of Alzheimer's",
    },
    {
      id: "D012",
      deceasedName: "Nina Singh",
      dod: "2023-11-30",
      tod: "15:15 PM",
      gender: "Female",
      age: "47",
      causeOfDeath: "Brain Tumor",
      doctorName: "Dr. Khanna",
      hospitalName: "Fortis Hospital",
      roomNumber: "210",
      notes: "After a long fight with cancer",
    },
    {
      id: "D013",
      deceasedName: "Amitabh Roy",
      dod: "2024-05-07",
      tod: "09:20 AM",
      gender: "Male",
      age: "83",
      causeOfDeath: "Old Age",
      doctorName: "Dr. Chatterjee",
      hospitalName: "Narayana Health",
      roomNumber: "403",
      notes: "Passed away peacefully",
    },
    {
      id: "D014",
      deceasedName: "Leela Nair",
      dod: "2023-08-17",
      tod: "20:45 PM",
      gender: "Female",
      age: "62",
      causeOfDeath: "Breast Cancer",
      doctorName: "Dr. Pillai",
      hospitalName: "Aster Hospital",
      roomNumber: "207",
      notes: "Under treatment for several months",
    },
    {
      id: "D015",
      deceasedName: "Rajesh Iyer",
      dod: "2023-02-25",
      tod: "07:35 AM",
      gender: "Male",
      age: "59",
      causeOfDeath: "Liver Cirrhosis",
      doctorName: "Dr. Kumar",
      hospitalName: "Apollo Hospital",
      roomNumber: "109",
      notes: "Chronic liver disease",
    },
    {
      id: "D016",
      deceasedName: "Meena Das",
      dod: "2024-03-12",
      tod: "11:50 AM",
      gender: "Female",
      age: "66",
      causeOfDeath: "COPD",
      doctorName: "Dr. Bose",
      hospitalName: "Ruby Hall Clinic",
      roomNumber: "312",
      notes: "Long-term respiratory issues",
    },
    {
      id: "D017",
      deceasedName: "Vikas Bhatia",
      dod: "2023-05-29",
      tod: "16:40 PM",
      gender: "Male",
      age: "73",
      causeOfDeath: "Stroke",
      doctorName: "Dr. Sen",
      hospitalName: "Fortis Hospital",
      roomNumber: "214",
      notes: "Complications from previous stroke",
    },
    {
      id: "D018",
      deceasedName: "Kavita Jain",
      dod: "2024-01-15",
      tod: "14:30 PM",
      gender: "Female",
      age: "57",
      causeOfDeath: "Pancreatic Cancer",
      doctorName: "Dr. Sharma",
      hospitalName: "Max Hospital",
      roomNumber: "306",
      notes: "Advanced stage of cancer",
    },
    {
      id: "D019",
      deceasedName: "Harish Rao",
      dod: "2023-06-23",
      tod: "09:10 AM",
      gender: "Male",
      age: "64",
      causeOfDeath: "Heart Attack",
      doctorName: "Dr. Kulkarni",
      hospitalName: "Holy Family Hospital",
      roomNumber: "213",
      notes: "Chronic heart disease",
    },
    {
      id: "D020",
      deceasedName: "Sneha Kulkarni",
      dod: "2023-04-12",
      tod: "13:25 PM",
      gender: "Female",
      age: "49",
      causeOfDeath: "Car Accident",
      doctorName: "Dr. Reddy",
      hospitalName: "Metro Hospital",
      roomNumber: "108",
      notes: "Brought in critical condition",
    },
    {
      id: "D021",
      deceasedName: "Amit Desai",
      dod: "2024-05-01",
      tod: "18:00 PM",
      gender: "Male",
      age: "80",
      causeOfDeath: "Old Age",
      doctorName: "Dr. Patel",
      hospitalName: "Noble Hospital",
      roomNumber: "501",
      notes: "Passed away peacefully",
    },
    {
      id: "D022",
      deceasedName: "Ragini Chauhan",
      dod: "2023-03-09",
      tod: "12:00 PM",
      gender: "Female",
      age: "68",
      causeOfDeath: "Kidney Failure",
      doctorName: "Dr. Lal",
      hospitalName: "Jehangir Hospital",
      roomNumber: "312",
      notes: "Long-term kidney disease",
    },
    {
      id: "D023",
      deceasedName: "Karan Kapoor",
      dod: "2022-08-30",
      tod: "15:30 PM",
      gender: "Male",
      age: "45",
      causeOfDeath: "Cardiac Arrest",
      doctorName: "Dr. Sood",
      hospitalName: "Sterling Hospital",
      roomNumber: "110",
      notes: "Sudden cardiac episode",
    },
    {
      id: "D024",
      deceasedName: "Pooja Singh",
      dod: "2024-02-22",
      tod: "07:45 AM",
      gender: "Female",
      age: "39",
      causeOfDeath: "Brain Hemorrhage",
      doctorName: "Dr. Verma",
      hospitalName: "Sunshine Hospital",
      roomNumber: "205",
      notes: "Sudden onset of symptoms",
    },
    {
      id: "D025",
      deceasedName: "Rajiv Mishra",
      dod: "2023-11-05",
      tod: "10:20 AM",
      gender: "Male",
      age: "63",
      causeOfDeath: "Diabetes Complications",
      doctorName: "Dr. Chawla",
      hospitalName: "Paras Hospital",
      roomNumber: "202",
      notes: "Advanced stage of diabetes",
    },
    {
      id: "D026",
      deceasedName: "Suman Tiwari",
      dod: "2024-01-27",
      tod: "14:55 PM",
      gender: "Female",
      age: "74",
      causeOfDeath: "Pneumonia",
      doctorName: "Dr. Banerjee",
      hospitalName: "Surya Hospital",
      roomNumber: "302",
      notes: "Underlying respiratory issues",
    },
    {
      id: "D027",
      deceasedName: "Arun Bhat",
      dod: "2023-12-19",
      tod: "11:05 AM",
      gender: "Male",
      age: "69",
      causeOfDeath: "Cancer",
      doctorName: "Dr. Das",
      hospitalName: "City Hospital",
      roomNumber: "410",
      notes: "Long battle with cancer",
    },
    {
      id: "D028",
      deceasedName: "Reena Sen",
      dod: "2023-07-14",
      tod: "16:35 PM",
      gender: "Female",
      age: "60",
      causeOfDeath: "Stroke",
      doctorName: "Dr. Rao",
      hospitalName: "Aster Hospital",
      roomNumber: "215",
      notes: "Complications from stroke",
    },
    {
      id: "D029",
      deceasedName: "Mukesh Patel",
      dod: "2024-03-03",
      tod: "06:50 AM",
      gender: "Male",
      age: "72",
      causeOfDeath: "Pneumonia",
      doctorName: "Dr. Shah",
      hospitalName: "Lilavati Hospital",
      roomNumber: "314",
      notes: "Underlying respiratory issues",
    },
    {
      id: "D030",
      deceasedName: "Aruna Nair",
      dod: "2023-06-27",
      tod: "19:00 PM",
      gender: "Female",
      age: "58",
      causeOfDeath: "Liver Failure",
      doctorName: "Dr. Pillai",
      hospitalName: "Aster Hospital",
      roomNumber: "112",
      notes: "Chronic liver disease",
    },
    {
      id: "D031",
      deceasedName: "Vikram Reddy",
      dod: "2023-01-10",
      tod: "04:30 AM",
      gender: "Male",
      age: "54",
      causeOfDeath: "Car Accident",
      doctorName: "Dr. Khanna",
      hospitalName: "Fortis Hospital",
      roomNumber: "104",
      notes: "Brought in critical condition",
    },
    {
      id: "D032",
      deceasedName: "Neeta Shah",
      dod: "2024-04-19",
      tod: "08:15 AM",
      gender: "Female",
      age: "67",
      causeOfDeath: "Cancer",
      doctorName: "Dr. Gupta",
      hospitalName: "Nanavati Hospital",
      roomNumber: "409",
      notes: "Long battle with cancer",
    },
    {
      id: "D033",
      deceasedName: "Rajan Joshi",
      dod: "2023-02-05",
      tod: "17:50 PM",
      gender: "Male",
      age: "65",
      causeOfDeath: "Heart Attack",
      doctorName: "Dr. Sinha",
      hospitalName: "Jaypee Hospital",
      roomNumber: "210",
      notes: "Chronic heart disease",
    },
    {
      id: "D034",
      deceasedName: "Snehal Desai",
      dod: "2023-09-09",
      tod: "12:20 PM",
      gender: "Female",
      age: "53",
      causeOfDeath: "Brain Tumor",
      doctorName: "Dr. Rao",
      hospitalName: "BLK Hospital",
      roomNumber: "405",
      notes: "Long fight with illness",
    },
    {
      id: "D035",
      deceasedName: "Sahil Kapoor",
      dod: "2022-11-28",
      tod: "09:30 AM",
      gender: "Male",
      age: "79",
      causeOfDeath: "Old Age",
      doctorName: "Dr. Chatterjee",
      hospitalName: "Narayana Health",
      roomNumber: "308",
      notes: "Peaceful passing",
    },
    {
      id: "D036",
      deceasedName: "Lata Verma",
      dod: "2023-03-17",
      tod: "14:45 PM",
      gender: "Female",
      age: "62",
      causeOfDeath: "Diabetes Complications",
      doctorName: "Dr. Sood",
      hospitalName: "Sterling Hospital",
      roomNumber: "204",
      notes: "Advanced stage of diabetes",
    },
  ];
  
  export default deathRecords;
  