const dummyMedData = [
    {
      serialNumber: "SN001",
      medicineName: "Paracetamol",
      dosageForm: "Tablet",
      quantity: 100,
      unitPrice: 2.5,
      availabilityStatus: "In Stock",
      prescriptionRequired: "No",
      history: [
        {
          date: "2020-01-05",
          description: "Initial purchase",
          manufacturer: "Johnson & Johnson",
          batchNumber: "B12345",
          expirationDate: "2023-12-31",
          supplierInformation: "McKesson Corporation",
        },
      ],
    },
    {
      serialNumber: "SN002",
      medicineName: "Ibuprofen",
      dosageForm: "Capsule",
      quantity: 50,
      unitPrice: 3.0,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2021-03-10",
          description: "Restock",
          manufacturer: "Pfizer Inc.",
          batchNumber: "B23456",
          expirationDate: "2024-06-30",
          supplierInformation: "Cardinal Health",
        },
      ],
    },
    {
      serialNumber: "SN003",
      medicineName: "Aspirin",
      dosageForm: "Tablet",
      quantity: 80,
      unitPrice: 1.8,
      availabilityStatus: "In Stock",
      prescriptionRequired: "No",
      history: [
        {
          date: "2022-05-15",
          description: "New batch",
          manufacturer: "Bayer AG",
          batchNumber: "B34567",
          expirationDate: "2024-12-31",
          supplierInformation: "CVS Health",
        },
      ],
    },
    {
      serialNumber: "SN004",
      medicineName: "Loratadine",
      dosageForm: "Tablet",
      quantity: 120,
      unitPrice: 2.2,
      availabilityStatus: "In Stock",
      prescriptionRequired: "No",
      history: [
        {
          date: "2021-07-20",
          description: "Restock",
          manufacturer: "GlaxoSmithKline plc",
          batchNumber: "B45678",
          expirationDate: "2023-08-31",
          supplierInformation: "Walgreens Boots Alliance",
        },
      ],
    },
    {
      serialNumber: "SN005",
      medicineName: "Omeprazole",
      dosageForm: "Capsule",
      quantity: 60,
      unitPrice: 2.7,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2023-02-28",
          description: "New stock",
          manufacturer: "AstraZeneca",
          batchNumber: "B56789",
          expirationDate: "2025-10-31",
          supplierInformation: "Express Scripts",
        },
      ],
    },
    {
      serialNumber: "SN006",
      medicineName: "Metformin",
      dosageForm: "Tablet",
      quantity: 90,
      unitPrice: 1.5,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2022-09-15",
          description: "Restock",
          manufacturer: "Merck & Co., Inc.",
          batchNumber: "B67890",
          expirationDate: "2024-04-30",
          supplierInformation: "AmerisourceBergen Corporation",
        },
      ],
    },
    {
      serialNumber: "SN007",
      medicineName: "Simvastatin",
      dosageForm: "Tablet",
      quantity: 70,
      unitPrice: 2.0,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2023-11-20",
          description: "New batch",
          manufacturer: "Novartis International AG",
          batchNumber: "B78901",
          expirationDate: "2025-07-31",
          supplierInformation: "Health Mart Systems, Inc.",
        },
      ],
    },
    {
      serialNumber: "SN008",
      medicineName: "Amoxicillin",
      dosageForm: "Capsule",
      quantity: 110,
      unitPrice: 2.3,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2021-05-10",
          description: "Initial purchase",
          manufacturer: "Gilead Sciences, Inc.",
          batchNumber: "B89012",
          expirationDate: "2023-09-30",
          supplierInformation: "The Kroger Co.",
        },
      ],
    },
    {
      serialNumber: "SN009",
      medicineName: "Cetirizine",
      dosageForm: "Tablet",
      quantity: 150,
      unitPrice: 1.7,
      availabilityStatus: "In Stock",
      prescriptionRequired: "No",
      history: [
        {
          date: "2022-08-05",
          description: "Restock",
          manufacturer: "Sanofi",
          batchNumber: "B90123",
          expirationDate: "2024-11-30",
          supplierInformation: "Rite Aid Corporation",
        },
      ],
    },
    {
      serialNumber: "SN010",
      medicineName: "Diazepam",
      dosageForm: "Tablet",
      quantity: 40,
      unitPrice: 2.8,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2023-04-18",
          description: "New batch",
          manufacturer: "Teva Pharmaceutical Industries Ltd.",
          batchNumber: "B01234",
          expirationDate: "2025-02-28",
          supplierInformation: "Albertsons Companies, Inc.",
        },
      ],
    },
    {
      serialNumber: "SN011",
      medicineName: "Prednisone",
      dosageForm: "Tablet",
      quantity: 130,
      unitPrice: 2.1,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2021-12-10",
          description: "Restock",
          manufacturer: "AbbVie Inc.",
          batchNumber: "B12345",
          expirationDate: "2023-06-30",
          supplierInformation: "Ahold Delhaize",
        },
      ],
    },
    {
      serialNumber: "SN012",
      medicineName: "Metoprolol",
      dosageForm: "Tablet",
      quantity: 75,
      unitPrice: 1.9,
      availabilityStatus: "In Stock",
      prescriptionRequired: "Yes",
      history: [
        {
          date: "2022-10-25",
          description: "New batch",
          manufacturer: "Bristol Myers Squibb",
          batchNumber: "B23456",
          expirationDate: "2024-09-30",
          supplierInformation: "Publix Super Markets, Inc.",
        },
      ],
    },
    {
      serialNumber: "SN0013",
      medicineName: "Paracetamol",
      dosageForm: "Tablet",
      quantity: 100,
      unitPrice: 2.5,
      availabilityStatus: "In Stock",
      prescriptionRequired: "No",
      history: [
        {
          date: "2020-01-05",
          description: "Initial purchase",
          manufacturer: "Manufacturer X",
          batchNumber: "B12345",
          expirationDate: "2023-12-31",
          supplierInformation: "Supplier Y",
        },
      ],
    },
  ];
  
  export default dummyMedData;
  