export const dummyData = [
    {
      id: 1,
      fullName: "John Doe",
      age: 35,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 2,
      fullName: "Jane Smith",
      age: 42,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 3,
      fullName: "Alice Johnson",
      age: 28,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 4,
      fullName: "Bob Brown",
      age: 50,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 5,
      fullName: "Charlie Lee",
      age: 45,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 6,
      fullName: "Ella Martinez",
      age: 38,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 7,
      fullName: "Frank Rodriguez",
      age: 55,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 8,
      fullName: "Grace Wilson",
      age: 47,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 9,
      fullName: "Henry Taylor",
      age: 33,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 10,
      fullName: "Ivy Clark",
      age: 40,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 11,
      fullName: "James Anderson",
      age: 39,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 12,
      fullName: "Linda Walker",
      age: 37,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 13,
      fullName: "Michael White",
      age: 44,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 14,
      fullName: "Sarah Adams",
      age: 29,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 15,
      fullName: "David Turner",
      age: 48,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 16,
      fullName: "Emily Harris",
      age: 36,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 17,
      fullName: "Robert Martinez",
      age: 52,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 18,
      fullName: "Olivia Thomas",
      age: 43,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 19,
      fullName: "William Young",
      age: 34,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 20,
      fullName: "Sophia Evans",
      age: 41,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 21,
      fullName: "Daniel Parker",
      age: 38,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 22,
      fullName: "Ava Collins",
      age: 36,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 23,
      fullName: "Christopher Reed",
      age: 43,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 24,
      fullName: "Mia Hill",
      age: 30,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 25,
      fullName: "Andrew Cooper",
      age: 47,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 26,
      fullName: "Abigail Rivera",
      age: 35,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 27,
      fullName: "Joseph Morgan",
      age: 50,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 28,
      fullName: "Charlotte Baker",
      age: 42,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 29,
      fullName: "Ethan Cox",
      age: 32,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 30,
      fullName: "Isabella Price",
      age: 43,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 31,
      fullName: "Alexander Hughes",
      age: 40,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 32,
      fullName: "Madison Perry",
      age: 35,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 33,
      fullName: "Gabriel Long",
      age: 42,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 34,
      fullName: "Samantha Gray",
      age: 27,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 35,
      fullName: "Jackson Cook",
      age: 46,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 36,
      fullName: "Madeline Coleman",
      age: 37,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 37,
      fullName: "Benjamin Ward",
      age: 53,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 38,
      fullName: "Avery Murphy",
      age: 44,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 39,
      fullName: "Natalie Brooks",
      age: 31,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 40,
      fullName: "Jackson Foster",
      age: 42,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 41,
      fullName: "Williamson Nguyen",
      age: 41,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 42,
      fullName: "Florence Ross",
      age: 33,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 43,
      fullName: "Frederick Peterson",
      age: 45,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 44,
      fullName: "Victoria Bennett",
      age: 28,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 45,
      fullName: "Harry Simmons",
      age: 49,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 46,
      fullName: "Liam Stewart",
      age: 39,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 47,
      fullName: "Emma Powell",
      age: 48,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 48,
      fullName: "Noah Kelly",
      age: 36,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 49,
      fullName: "Mia Richardson",
      age: 33,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 50,
      fullName: "Jacob Murphy",
      age: 40,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 51,
      fullName: "Sophia Cooper",
      age: 41,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 52,
      fullName: "Oliver Evans",
      age: 34,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 53,
      fullName: "Ava Nelson",
      age: 42,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 54,
      fullName: "Elijah Hughes",
      age: 27,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 55,
      fullName: "Charlotte Barnes",
      age: 46,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 56,
      fullName: "Lucas Rivera",
      age: 37,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 57,
      fullName: "Isabella Simmons",
      age: 53,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 58,
      fullName: "Mason Ward",
      age: 44,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 59,
      fullName: "Harper Brooks",
      age: 31,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 60,
      fullName: "Evelyn Foster",
      age: 42,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 61,
      fullName: "Logan Nguyen",
      age: 41,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 62,
      fullName: "Luna Ross",
      age: 33,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 63,
      fullName: "Mateo Peterson",
      age: 45,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 64,
      fullName: "Nova Bennett",
      age: 28,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 65,
      fullName: "Eli Hill",
      age: 49,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 66,
      fullName: "Aurora Stewart",
      age: 39,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 67,
      fullName: "Jackson Powell",
      age: 48,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 68,
      fullName: "Liam Kelly",
      age: 36,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 69,
      fullName: "Emma Richardson",
      age: 33,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 70,
      fullName: "Jacob Murphy",
      age: 40,
      department: "Dentistry",
      status: "Active",
    },
    {
      id: 71,
      fullName: "Sophia Cooper",
      age: 41,
      department: "Cardiology",
      status: "Active",
    },
    {
      id: 72,
      fullName: "Oliver Evans",
      age: 34,
      department: "Pediatrics",
      status: "Inactive",
    },
    {
      id: 73,
      fullName: "Ava Nelson",
      age: 42,
      department: "Orthopedics",
      status: "Active",
    },
    {
      id: 74,
      fullName: "Elijah Hughes",
      age: 27,
      department: "Dermatology",
      status: "Active",
    },
    {
      id: 75,
      fullName: "Charlotte Barnes",
      age: 46,
      department: "Neurology",
      status: "Inactive",
    },
    {
      id: 76,
      fullName: "Lucas Rivera",
      age: 37,
      department: "Gynecology",
      status: "Active",
    },
    {
      id: 77,
      fullName: "Isabella Simmons",
      age: 53,
      department: "Ophthalmology",
      status: "Active",
    },
    {
      id: 78,
      fullName: "Mason Ward",
      age: 44,
      department: "Psychiatry",
      status: "Inactive",
    },
    {
      id: 79,
      fullName: "Harper Brooks",
      age: 31,
      department: "General Medicine",
      status: "Active",
    },
    {
      id: 80,
      fullName: "Evelyn Foster",
      age: 42,
      department: "Dentistry",
      status: "Active",
    },
  ];
  